/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author profesor
 */
public class Inicio extends javax.swing.JFrame {
    
    public Inicio(String usuario) {
        initComponents();
        jLabelSaludo.setText("Hola " + usuario);
        iniciarModelos();
    }

    
    private void iniciarModelos(){
        modeloBebidas = new DefaultComboBoxModel();
        modeloPizzas = new DefaultComboBoxModel();
        modeloBebidas.addElement("Colacola");
        modeloBebidas.addElement("Agua");
        modeloBebidas.addElement("Nestea");
        modeloPizzas.addElement("Carbonara");
        modeloPizzas.addElement("4 quesos");
        modeloPizzas.addElement("Barbacoa");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSaludo = new javax.swing.JLabel();
        jComboBoxTipoProductos = new javax.swing.JComboBox<>();
        jComboBoxBebidasORPizzas = new javax.swing.JComboBox<>();
        jButtonEncargar = new javax.swing.JButton();
        jLabelEncargos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextFieldNewProducto = new javax.swing.JTextField();
        jButtonAddProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSaludo.setText("Hola usuario");

        jComboBoxTipoProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto:", "Bebida", "Pizza" }));
        jComboBoxTipoProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTipoProductosMouseClicked(evt);
            }
        });
        jComboBoxTipoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoProductosActionPerformed(evt);
            }
        });

        jComboBoxBebidasORPizzas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingredientes:", "Tomate", "Nata", "Oregano", "Queso" }));

        jButtonEncargar.setText("Encargar");
        jButtonEncargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEncargarMouseClicked(evt);
            }
        });

        jLabelEncargos.setText("Encargos");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextFieldNewProducto.setText("Nuevo producto");

        jButtonAddProducto.setText("Añadir");
        jButtonAddProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddProductoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTipoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonEncargar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxBebidasORPizzas, javax.swing.GroupLayout.Alignment.LEADING, 0, 132, Short.MAX_VALUE))
                    .addComponent(jLabelSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNewProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButtonAddProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEncargos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jLabelEncargos)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTipoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNewProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxBebidasORPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEncargar)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEncargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEncargarMouseClicked
        String producto;
        
        
        producto = (String) jComboBoxBebidasORPizzas.getSelectedItem();
        
        if (jTextArea1.getText().equals("")) {
            jTextArea1.setText(producto);
        }else
            jTextArea1.setText(jTextArea1.getText() + "\n" +producto);
        
    }//GEN-LAST:event_jButtonEncargarMouseClicked

    private void jComboBoxTipoProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoProductosMouseClicked
       
        
        
    }//GEN-LAST:event_jComboBoxTipoProductosMouseClicked

    private void jComboBoxTipoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoProductosActionPerformed
        int opc = jComboBoxTipoProductos.getSelectedIndex();
        
        switch (opc){
            case 0:
                JOptionPane.showMessageDialog(rootPane, "Seleccione un producto","",2);
                break;
            case 1:
                jComboBoxBebidasORPizzas.setModel(modeloBebidas);
                break;
            case 2:
                jComboBoxBebidasORPizzas.setModel(modeloPizzas);
                break;
        }
    }//GEN-LAST:event_jComboBoxTipoProductosActionPerformed

    private void jButtonAddProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddProductoMouseClicked
        String nuevo = "";
        
        if (jTextFieldNewProducto.getText().equalsIgnoreCase("nuevo producto") || jTextFieldNewProducto.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "Escribe algo por favor", "", 1);
        }else{
            switch (jComboBoxTipoProductos.getSelectedIndex()){
                case 0:
                    JOptionPane.showMessageDialog(rootPane, "Escoje la lista a la que añadir el producto (Pizza o Bebidas)", "", 1);
                    break;
                case 1:
                    nuevo=jTextFieldNewProducto.getText();
                    modeloBebidas.addElement(nuevo);
                    break;
                case 2:
                    nuevo=jTextFieldNewProducto.getText();
                    modeloPizzas.addElement(nuevo);
                    break;
            }
        }
            
            
            
            
            
            
        
        
    }//GEN-LAST:event_jButtonAddProductoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio("Juan").setVisible(true);
            }
        });
    }

    private javax.swing.DefaultComboBoxModel<String> modeloBebidas;
    private javax.swing.DefaultComboBoxModel<String> modeloPizzas;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddProducto;
    private javax.swing.JButton jButtonEncargar;
    private javax.swing.JComboBox<String> jComboBoxBebidasORPizzas;
    private javax.swing.JComboBox<String> jComboBoxTipoProductos;
    private javax.swing.JLabel jLabelEncargos;
    private javax.swing.JLabel jLabelSaludo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldNewProducto;
    // End of variables declaration//GEN-END:variables
}
